config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'
  resources :notes
  get 'users/:id/follow', to: 'followers#follow', as: :follow
  get 'users/:id/unfollow' => 'followers#unfollow', as: :unfollow 
  get '/other_users' => 'users#other_users' 
  get 'notes/:id/upvote', to: 'votes#upvote', as: :upvote
  get 'notes/:id/downvote' => 'votes#downvote', as: :downvote 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follower.rb
class Follower < ApplicationRecord
	belongs_to :user
end

app/models/note.rb
class Note < ApplicationRecord
	belongs_to :user
	has_many :votes, dependent: :destroy

	def count_upvote
		self.votes.where(count: 1).count
	end

	def count_downvote
		self.votes.where(count: 0).count
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :notes, dependent: :destroy
  has_many :followers, dependent: :destroy
  validates :email, :password , presence: true
  validates :email, uniqueness: true

	def count_follow
		self.followers.where(count: 1).count
	end

	def count_unfollow
		self.followers.where(count: 0).count
	end
end

app/models/vote.rb
class Vote < ApplicationRecord
	belongs_to :note
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
	before_action :require_login,  only: [:follow, :unfollow]

	def follow
		set_follow_user
		#check if user has already followed the particular user
		@followed = Follower.find_by(user_id: @follow.id, follow_id: current_user.id)
		if @followed 
			if @followed.count == 1
				redirect_to '/', notice: 'You can follow only once'
			elsif @followed.count == 0
				@followed.update(count: 1)
				redirect_to '/', notice: "You are following the user #{@follow.email}"				
			end
		else	
		#create a record of the current user and followed user	
			@follower = Follower.new
			@follower.user_id = @follow.id	
			@follower.follow_id = current_user.id					
			@follower.count = 1
			if @follower.save
				redirect_to '/', notice: "You are following the user #{@follow.email}"
			else
				render :'/', notice: 'Please try again'
			end
		end
	end

	def unfollow
		set_follow_user
		#check if user has already unfollowed the particular user
		@followed = Follower.find_by(user_id: @follow.id, follow_id: current_user.id)
		if @followed 
			if @followed.count == 0
				redirect_to '/', notice: 'You can unfollow only once'
			elsif @followed.count == 1
				@followed.update(count: 0)
				redirect_to '/', notice: "You are unfollowing the user #{@follow.email}"			
			end	
		else	
		#create a record of the current user and unfollowed user	
			@follower = Follower.new
			@follower.user_id = @follow.id	
			@follower.follow_id = current_user.id					
			@follower.count = 0
			if @follower.save
				redirect_to '/', notice: "You are unfollowing the user #{@follow.email}"
			else
				render :'/', notice: 'Please try again'
			end
		end
	end	

	private

	def follower_params
		process_params = params.require(:follower).permit(user_id, follow_id, count)
	end

	def set_follow_user
		@follow = User.find(params[:id])
	end	

    def require_login
		unless user_signed_in?
			flash[:alert] = "You must be logged in to access this section"
			redirect_to '/users/sign_in'
		end
	end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	before_action :require_login,  only: [:new, :edit, :create, :update, :destroy]	
	before_action :authenticate_user!, only: [:new, :create, :update, :destroy]
	before_action :get_note, only: [:show, :edit, :update, :destroy]
	before_action :user_process, only: [:edit, :update, :destroy]


	def index
		@notes = current_user.notes
	end
		
	def new
		@note = Note.new
	end

	def create
		@note = current_user.notes.create(note_params)
		if @note.save
			redirect_to @note, notice: 'Note was successfully created.'
		else
			render :new
		end
	end

	def show
	end

	def edit
	end

	def update
		if @note.update(note_params)
			redirect_to @note, notice: 'Note was updated successfully.'
		else
			render :edit
		end
	end

	def destroy
		@note.destroy
		redirect_to notes_url, notice: 'Note was deleted successfully.'
	end


	private
	def note_params
		params.require(:note).permit(:content)
	end

	def get_note
		@note = Note.find(params[:id])
	end

    def require_login
		unless user_signed_in?
			flash[:alert] = "You must be logged in to access this section"
			redirect_to '/users/sign_in'
		end
	end

	def user_process
		unless current_user.id == @note.user_id
			flash[:alert] = "You can perform actions only on notes created by you"
			redirect_to '/'
		end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_login,  only: [:other_users]

	def index
		if user_signed_in?
			@users = Follower.where("follow_id=? AND count=?", current_user.id.to_i, 1)
			@user_array = []
			@users.each do |user|
				@user_array << User.find(user.user_id)
			end
		end
	end
	def other_users
			#get users i follow
			@users_i_follow = Follower.where("follow_id=? AND count=?", current_user.id, 1)
			#minus from total users to find users i dont follow
			@users_i_follow_id = @users_i_follow.pluck(:user_id)
			@users_i_dont_follow = User.all.pluck(:id) - @users_i_follow_id
			@user_array = []
			@users_i_dont_follow.each do |id|
				@user_array << User.find(id)
			end
	end

	private
    def require_login
		unless user_signed_in?
			flash[:alert] = "You must be logged in to access this section"
			redirect_to '/users/sign_in'
		end
	end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

	before_action :require_login,  only: [:upvote, :downvote]

	def upvote
		set_note
		#check if note is upvoted
		@vote = Vote.find_by(note_id: @note.id, user_id: current_user.id)
		if @vote
			if @vote.count == 1
				redirect_to note_path(@note.id), notice: 'You can upvote only once'
			elsif @vote.count == 0
				@vote.update(count: 1)
				UserMailer.notify_email(@note.user, 1).deliver_now
				redirect_to note_path(@note.id), notice: "You have upvoted #{@note.content}"				
			end
		else	
		#create a record of the note being upvoted
			@vote = Vote.new
			@vote.note_id = @note.id
			@vote.user_id = current_user.id
			@vote.count = 1
			if @vote.save
				UserMailer.notify_email(@note.user, 1).deliver_now
				redirect_to note_path(@note.id), notice: "You have upvoted #{@note.content}"	
			else
				render :'/', notice: 'Please try again'
			end
		end
	end

	def downvote
		set_note
		#check if note is downvoted
		@vote = Vote.find_by(note_id: @note.id, user_id: current_user.id)
		if @vote
			if @vote.count == 0
				redirect_to note_path(@note.id), notice: 'You can downvote only once'
			elsif @vote.count == 1
				@vote.update(count: 0)
				UserMailer.notify_email(@note.user, 0).deliver_now				
				redirect_to note_path(@note.id), notice: "You have downvoted #{@note.content}"			
			end	
		else	
		#create a record of the note bering downvoted	
			@note = Note.new
			@vote.note_id = @note.id
			@vote.user_id = current_user.id
			@vote.count = 0
			if @vote.save
				UserMailer.notify_email(@note.user, 0).deliver_now				
				redirect_to note_path(@note.id), notice: "You have downvoted #{@vote.content}"
			else
				render :'/', notice: 'Please try again'
			end
		end
	end	

	private

	def vote_params
		process_params = params.require(:vote).permit(vote_id, count, user_id)
	end

	def set_note
		@note = Note.find(params[:id])
	end	

    def require_login
		unless user_signed_in?
			flash[:alert] = "You must be logged in to access this section"
			redirect_to '/users/sign_in'
		end
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyAcFinalAssessment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">NoteMaker</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <%if current_user %>
              <li><a href="/notes"><%=current_user.email%></a></li>
            <%end%>  
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">User List<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="/">Users I follow</a></li>
                <li><a href="/other_users">Other Users</a></li>
                <li><a href="/notes/new">Create a note</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
          	<% if current_user %>
            	<li><%= link_to "Logout" , destroy_user_session_path, method: :delete  %>
            	</li>
            <%else%>
            	<li><a href="/users/sign_in">Login</a></li>
            <%end%>		
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <div class="container-fluid" style="margin-left: 30px;">
    <div style="text-align: center; color:red;">
      <%- flash.each do |name, msg| -%>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      <%- end -%>  
    </div> 
    <%= yield %>
    </div>

  </body>
</html>

app/views/notes/_form.html.erb
<div class="row"> 
  <div class="col-md-6">
  <%= form_for(@note) do |form| %>
    <%= form.label :Note %>
    <%= form.text_area :content, class: "form-control"%>
    <%= form.submit %>
  <%end%>
  </div>
</div>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', root_path %>

app/views/notes/index.html.erb
<h3 style="text-align: center">Display my notes</h3>

<div style="margin-left:50px">
	<%@notes.each do |note|%>
		<%=note.content%>
		<%=link_to raw("   upvote-#{note.count_upvote}"), upvote_path(note.id)%> <%=link_to raw("   downvote-#{note.count_downvote}"), downvote_path(note.id) %>
		<hr>
	<%end%>	
</div>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/notes/show.html.erb
<h2>My Notes</h2>
<div class="row" style="margin-left: 30px;">
	<%=@note.content%>
	<%=link_to raw("   upvote-#{@note.count_upvote}"), upvote_path(@note.id)%> <%=link_to raw("   downvote-#{@note.count_downvote}"), downvote_path(@note.id) %>
</div>	
<br>
	<%= link_to "Edit", edit_note_path(@note) %>
	<%= link_to 'Destroy', @note, method: :delete, data: { confirm: 'Are you sure?' } %>
<br>
<%= link_to 'Back to User Notes', root_path %>

app/views/users/index.html.erb
<%if current_user%>
	<div style="margin-left:50px">
	<%= link_to 'Create a note', new_note_path %>
	<h3 style="text-align: center">Display Users I follow</h3>

	<% @user_array.each do |user| %>
		<h5><%= user.email %><%=link_to raw("   follow-#{user.count_follow}"), follow_path(user.id)%> <%=link_to raw("   unfollow-#{user.count_unfollow}"), unfollow_path(user.id) %></h5>
		<%user.notes.each do |note|%>
			<p><%=note.content%>  <%=link_to 'Show', note %></p>
		<%end%>	
		<hr>
	<%end%>	
<%end%>	
</div>

<h3 style="text-align: center">Display all Users with their Notes</h3>

<div style="margin-left:50px">
	<%User.all.each do |user|%>
		<h5><%=user.email%><%=link_to raw("   follow-#{user.count_follow}"), follow_path(user.id)%> <%=link_to raw("   unfollow-#{user.count_unfollow}"), unfollow_path(user.id) %></h5>
		<%user.notes.each do |note|%>
			<p><%=note.content%>  <%=link_to 'Show', note %></p>
		<%end%>	
		<hr>
	<%end%>	
</div>

app/views/users/other_users.html.erb
<h3 style="text-align: center">Users I don't follow</h3>

	<% @user_array.each do |user| %>
		<h5><%=user.email%><%=link_to raw("   follow-#{user.count_follow}"), follow_path(user.id)%> <%=link_to raw("   unfollow-#{user.count_unfollow}"), unfollow_path(user.id) %></h5>
		<%user.notes.each do |note|%>
			<p><%=note.content%>  <%=link_to 'Show', note %></p>
		<%end%>	
		<hr>
	<%end%>	
	<%= link_to 'Create a note', new_note_path %>